services:
  api_gateway:
    image: nginx:1.27.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./googleImg.png:/usr/share/nginx/html/googleImg.png
    ports:
      - "8080:80"
